# .github/ISSUE_TEMPLATE/bug_report.yml
name: 🐛 Bug Report
description: File a bug report
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    attributes:
      label: What happened?
      description: A clear description of the bug
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior
    validations:
      required: true
  - type: input
    attributes:
      label: Version
      description: What version of the package are you running?
    validations:
      required: true